import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
})
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
})

export const metadata: Metadata = {
	title: 'my app',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<head>
				<meta charSet='utf-8' />
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1, shrink-to-fit=no'
				/>
				<meta
					name='theme-color'
					content='#000000'
				/>
				<meta
					name='description'
					content={metadata.description ?? ''}
				/>
				<title>{String(metadata.title)}</title>
				<link
					rel='icon'
					href='/favicon.ico'
				/>

				<link
					rel='apple-touch-icon'
					href='/logo192.png'
				/>
				<link
					rel='manifest'
					href='/manifest.json'
				/>
				{geistSans.preload}
				{geistMono.preload}
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	)
}
